services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      API_BASE_URL: http://api:8000
    depends_on:
      - api
    
    stdin_open: true
    tty: true

    command:
      - streamlit
      - run
      - dashboard/app.py
      - --server.address=0.0.0.0
      - --server.port=8501
      - --server.fileWatcherType=none